export type Accidental = '♮' | '♯' | '♭'
export type Note
  = | 'C'
    | 'D'
    | 'E'
    | 'F'
    | 'G'
    | 'A'
    | 'B'
    | 'F♯'
    | 'C♯'
    | 'G♯'
    | 'D♯'
    | 'A♯'
    | 'B♭'
    | 'E♭'
    | 'A♭'
    | 'D♭'
    | 'G♭'
export type SingleNoteList = Array<Note>
export type MultiNoteList = Array<Note | Array<Note>>
export type CircleOfFifthList = Array<{ major: Note, minor: Note }>
export type Interval
  = | 'P1'
    | 'm2'
    | 'M2'
    | 'm3'
    | 'M3'
    | 'd4'
    | 'P4'
    | 'A4'
    | 'd5'
    | 'P5'
    | 'A5'
    | 'm6'
    | 'M6'
    | 'm7'
    | 'M7'
    | 'P8'

export type Semitone = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12
export type Mode
  = | 'Ionian'
    | 'Dorian'
    | 'Phrygian'
    | 'Lydian'
    | 'Mixolydian'
    | 'Aeolian'
    | 'Locrian'
    | 'Major Pentatonic'
    | 'Minor Pentatonic'
    | 'Mixolydian Pentatonic'
    | 'Blues Scale'
    | 'Bebop Major'
    | 'Bebop Minor'
    | 'Bebop Dominant'
    | 'Bebop Dorian'
    | 'Harmonic Minor'
    | 'Melodic Minor'
    | 'Lydian Dominant'
    | 'Altered'

export type ModeList = Array<Mode>
export type ModeIntervalMap = Record<Mode, Array<Interval>>
